
# Windows Build Configuration for AppVeyor
# http://www.appveyor.com/docs/appveyor-yml

# build version format
version: "{build}"

os: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - master
    - dev

# scripts that run after cloning repository
install:
#  - git clone https://github.com/KhronosGroup/glslang.git ../glslang
#  - git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git ../Vulkan-LoaderAndValidationLayers

build:
  parallel: true  # enable MSBuild parallel builds
  verbosity: minimal

build_script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config %CONFIGURATION%

test_script:

notifications:
  - provider: Email
    to:
      - rene@lunarg.com
    subject: 'Vulkan-Samples Windows Build #{{buildVersion}}: {{status}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
